<a href="https://colab.research.google.com/github/sfragkoul/Intro/blob/main/2_Numpy_PUBLIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook by Stella Fragkouli based on "Introduction to Scientific Computing in Python" by Robert Johansson. 


Aristotle University of Thessaloniki

v1.0 (March 2021)

# Chapter 3: Numpy - multidimensional data arrays

The numpy package (module) is used in almost all numerical computation using Python. It is a package
that provide high-performance vector, matrix and higher-dimensional data structures for Python.

In the numpy package the terminology used for vectors, matrices and higher-dimensional data sets is
**array**

In [1]:
import numpy as np

### 3.2 Creating numpy arrays

There are a number of ways to initialize new numpy arrays, for example from

• a Python list or tuples

• using functions that are dedicated to generating numpy arrays, such as arange, linspace, etc.

• reading data from files

In [13]:
#a vector: the argument to the array function is a Python list
v = np.array([1,2,3,4]) # is a single dimensional array of 4 elements
print(v,type(v))
v.shape

[1 2 3 4] <class 'numpy.ndarray'>


(4,)

In [14]:
# a matrix: the argument to the array function is a nested Python list
M = np.array([[1, 2], [3, 4], [5, 6]]) #is a two - dimensional array which is composed of 3 single dimensional arrays
print(M,type(M))
M.shape # same as np.shape(M)

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>


(3, 2)

[Numpy shape() documentation](https://numpy.org/doc/stable/reference/generated/numpy.shape.html)

In [15]:
M.size #number of elements in the array

6

So far the numpy.ndarray looks awefully much like a Python list (or nested list). Why not simply use Python lists for computations instead of creating a new array type?

There are several reasons:

• Python lists are very general. They can contain any kind of object. They are dynamically typed. They do not support mathematical functions such as matrix and dot multiplications, etc. 

• NumPy arrays are mutable, which means that you can change the value of an element in the array after an array has been initialized [ stackoverflow](https://stackoverflow.com/questions/5541324/immutable-numpy-array)

• Numpy arrays are memory efficient.

• Because of the static typing, fast implementation of mathematical functions such as multiplication and
addition of numpy arrays can be implemented in a compiled language (C and Fortran is used).

In [20]:
M.dtype #returns what type the data of an array has

dtype('int64')

In [ ]:
#We get an error if we try to assign a value of the wrong type to an element in a numpy array
M[0,0] = "hello"

In [22]:
# we can explicitly define the type of the array data when we create it, using the dtype keyword argument:
M = np.array([[1, 2], [3, 4]], dtype=complex)
print(M)

#We can also explicitly define the bit size of the data types, for example: int16, float64, complex128

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [25]:
# create a range
x = np.arange(0, 10, 1) # arguments: start, stop, step
x
#x.shape

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
x = np.arange(-1, 1, 0.1)
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

In [28]:
# using linspace, *both end points ARE included*!!!
np.linspace(0, 10, 25) #(start, stop, num=50)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [30]:


np.logspace(0, 10, 10, base=e)

#can you guess the error here?

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

In [34]:
x, y = np.mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [32]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [36]:
from numpy import random

# uniform random numbers in [0,1]
random.rand(5,5)

array([[0.10542871, 0.33515915, 0.54858164, 0.40066802, 0.75289059],
       [0.29146932, 0.81037655, 0.35596955, 0.68598895, 0.78396426],
       [0.59162627, 0.48764639, 0.15072915, 0.03089668, 0.70633608],
       [0.78876611, 0.95924195, 0.48057423, 0.41753717, 0.11742762],
       [0.55661422, 0.04470073, 0.17183148, 0.18883154, 0.69057948]])

In [37]:
# standard normal distributed random numbers
random.randn(5,5)

array([[ 6.99967196e-01, -7.77572186e-01, -1.41944450e+00,
        -7.99536985e-01, -3.93469105e+00],
       [ 1.35654510e-01, -2.76077212e-01,  1.29009854e-01,
         3.40811819e-01,  3.27394004e-01],
       [-4.88785936e-01, -1.18595228e+00, -5.52079861e-01,
         3.33312561e-01,  2.48310633e-02],
       [-3.78451338e-01,  3.42021481e-01,  1.41158969e-03,
        -9.92350236e-01, -1.74448926e-01],
       [ 9.73797037e-01, -1.89040695e-01, -4.55409901e-01,
         1.11270388e+00,  1.22996734e+00]])

In [38]:
# a diagonal matrix
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [43]:
# diagonal with offset from the main diagonal
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [44]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [45]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
M=np.eye(6)
M

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### Numpy's native file format

In [48]:
np.save("eye-matrix.npy", M)


In [49]:
np.load("eye-matrix.npy")

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### 3.5 Manipulating arrays

In [50]:
M = np.array([[1, 2], [3, 4], [5, 6]])
print(M)

[[1 2]
 [3 4]
 [5 6]]


In [51]:
## M is a matrix, or a 2 dimensional array, taking two indices

M[1,1]

4

In [52]:
# If we omit an index of a multidimensional array it returns the whole row
M[0]

array([1, 2])

In [53]:
#The same thing can be achieved with using : instead of an index
M[1,:]

array([3, 4])

In [54]:
M[0,0] = 10
M

array([[10,  2],
       [ 3,  4],
       [ 5,  6]])

In [55]:
#@title Exercise Numpy Index
# also works for rows and columns
M[1,:] = 0
M[:,1] = -1
M

array([[10, -1],
       [ 0, -1],
       [ 5, -1]])

In [58]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [59]:
A[1:3]

array([2, 3])

In [60]:
# Array slices are mutable: if they are assigned a new value the original array is modified
A[1:3] = [-2,-3]
A

array([ 1, -2, -3,  4,  5])

In [67]:
A = np.array([[m+n*10 for n in range(5)] for m in range(5)])
A

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [68]:
# a block from the original array
A[1:4, 1:4]

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [69]:
# strides
A[::2, ::2]

array([[ 0, 20, 40],
       [ 2, 22, 42],
       [ 4, 24, 44]])

**index masks**:  If the index mask is an Numpy array of data type bool, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element

In [72]:
B = np.array([n for n in range(5)])
B

array([0, 1, 2, 3, 4])

In [73]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

This feature is very useful to conditionally select elements from an array, using for example comparison
operators

In [74]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [75]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

Fancy indexing is conceptually simple: it means passing an array of indices to access multiple array elements at once

In [76]:
x[mask] #fancy indexing

array([5.5, 6. , 6.5, 7. ])

### 3.6 Functions for extracting data from arrays and creating arrays

**where**

The index mask can be converted to position index using the where function

In [77]:
indices = np.where(mask) #tells us where this is true
indices

(array([11, 12, 13, 14]),)

In [78]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

**diag**
With the diag function we can also extract the diagonal and subdiagonals of an array

In [82]:
A = np.array([[m+n*10 for n in range(5)] for m in range(5)]) # like before
A
#np.diag(A)

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [81]:
np.diag(A, -2)

array([ 2, 13, 24])

### 3.7 Linear algebra

Vectorizing code is the key to writing eficient numerical calculation with Python/Numpy. That means
that as much as possible of a program should be formulated in terms of matrix and vector operations, like
matrix-matrix multiplication.

In [106]:
#Scalar-array operations

v1 = np.arange(0, 5)
v2=v1 * 2

In [84]:
A

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [85]:
#Element-wise array-array operations. the default behaviour is element-wise

A * A # element-wise multiplication

array([[   0,  100,  400,  900, 1600],
       [   1,  121,  441,  961, 1681],
       [   4,  144,  484, 1024, 1764],
       [   9,  169,  529, 1089, 1849],
       [  16,  196,  576, 1156, 1936]])

In [86]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [87]:
#If we multiply arrays with compatible shapes, we get an element-wise multiplication of each row
A.shape, v1.shape

((5, 5), (5,))

In [96]:
A * v1

array([[  0,  10,  40,  90, 160],
       [  0,  11,  42,  93, 164],
       [  0,  12,  44,  96, 168],
       [  0,  13,  46,  99, 172],
       [  0,  14,  48, 102, 176]])

In [97]:
#matrix mutiplication
np.dot(A, A)

array([[ 300, 1300, 2300, 3300, 4300],
       [ 310, 1360, 2410, 3460, 4510],
       [ 320, 1420, 2520, 3620, 4720],
       [ 330, 1480, 2630, 3780, 4930],
       [ 340, 1540, 2740, 3940, 5140]])

In [98]:
np.dot(A, v1)

array([300, 310, 320, 330, 340])

**matrix**: Returns a matrix from an array-like object, or from a string of data. A matrix is a specialized 2-D array that retains its 2-D nature through operations. It has certain special operators, such as * (matrix multiplication) and ** (matrix power).

In [108]:
M = np.matrix(A)
v = np.matrix(v1).T # make it a column vector
v.shape

(5, 1)

In [111]:
#If we try to add, subtract or multiply objects with incomplatible shapes we get an error
v = np.matrix([1,2,3,4,5,6]).T
np.shape(M), np.shape(v)

((5, 5), (6, 1))

In [118]:
M * v


ValueError: ignored

In [119]:
#Data processing

from numpy import genfromtxt
data = genfromtxt('/content/sample_data/mnist_test.csv', delimiter=',')

In [120]:
data.shape

(10000, 785)

In [121]:
np.mean(data[0,:])

23.5171974522293

In [122]:
#mean per row
np.mean(data,axis=1)

array([23.51719745, 36.75414013, 12.57579618, ..., 37.24203822,
       33.83949045, 53.29808917])

In [123]:
#mean per column
np.mean(data,axis=0)

array([4.443400e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 3.800000e-03, 2.360000e-02,
       1.580000e-02, 4.030000e-02, 5.110000e-02, 1.047000e-01,
       2.343000e-01, 3.088000e-01, 2.660000e-01, 3.081000e-01,
       2.343000e-01, 6.910000e-02, 8.970000e-02, 9.400000e-02,
       5.020000e-02, 1.920000e-02, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 4.370000e-02, 1.1150

In [124]:
print(data[1,:].max())
print(data[1,:].min())

255.0
0.0


### 3.8 Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast
operation even for large arrays.

In [125]:
A = np.array([[m+n*10 for n in range(5)] for m in range(5)]) # like before
A

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [126]:
n, m = A.shape
n,m

(5, 5)

In [129]:
B = A.reshape((1,n*m))
B

array([[ 0, 10, 20, 30, 40,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3,
        13, 23, 33, 43,  4, 14, 24, 34, 44]])

In [130]:
A

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [131]:
B[0,0:5] = 5 # modify the array
B

array([[ 5,  5,  5,  5,  5,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3,
        13, 23, 33, 43,  4, 14, 24, 34, 44]])

In [132]:
A ## and the original variable is also changed. B is only a different view of the same data

array([[ 5,  5,  5,  5,  5],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

In [135]:
#the function flatten makes a higher-dimensional array into a vector. But this function creates a copy of the data.

C = A.flatten()
C

array([ 5,  5,  5,  5,  5,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3, 13,
       23, 33, 43,  4, 14, 24, 34, 44])

In [136]:
C[0:5] = 10
C

array([10, 10, 10, 10, 10,  1, 11, 21, 31, 41,  2, 12, 22, 32, 42,  3, 13,
       23, 33, 43,  4, 14, 24, 34, 44])

In [137]:
A

array([[ 5,  5,  5,  5,  5],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44]])

### 3.9 Adding a new dimension: newaxis

With **newaxis**, we can insert new dimensions in an array, for example converting a vector to a column or
row matrix

In [141]:
v = np.array([1,2,3])
np.shape(v)

(3,)

In [151]:
# make a column matrix of the vector v
v[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [152]:
# column matrix
v[:,np.newaxis].shape

(3, 1)

In [153]:
# row matrix
v[np.newaxis,:].shape

(1, 3)

### 3.10 Stacking and repeating arrays

**tile** and **repeat**

In [156]:
a = np.array([[1, 2], [3, 4]])
a
a.shape

(2, 2)

In [160]:
# repeat each element 3 times
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [163]:
# tile the matrix 3 times
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

**concatenate**

In [165]:
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [166]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

**hstack** and **vstack**

In [167]:
np.vstack((a,b)) #same as np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [168]:
np.hstack((a,b.T))#same as np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

### 3.11 Copy and deep copy

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is
important for example when objects are passed between functions, to avoid an excessive amount of memory
copying when it is not necessary (technical term: pass by reference).

In [169]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [170]:
# now B is referring to the same array data as A
B = A
B

array([[1, 2],
       [3, 4]])

In [171]:
# changing B affects A
B[0,0] = 10
B

array([[10,  2],
       [ 3,  4]])

In [172]:
A

array([[10,  2],
       [ 3,  4]])

If we want to avoid this behavior, so that when we get a new completely independent object B copied
from A, then we need to do a so-called "deep copy" using the function **copy**

In [173]:
D = np.copy(A)
D

array([[10,  2],
       [ 3,  4]])

In [174]:
# now, if we modify B, A is not affected
D[0,0] = -5
D

array([[-5,  2],
       [ 3,  4]])

In [175]:
A

array([[10,  2],
       [ 3,  4]])

### 3.12 Iterating over array elements

In [176]:
v = np.array([1,2,3,4])

for element in v:
  print(element)

1
2
3
4


When we need to iterate over each element of an array and modify its elements, it is convenient to use
the **enumerate** function to obtain both the element and its index in the for loop

In [177]:
grocery = ['bread', 'milk', 'butter']
enumerateGrocery = enumerate(grocery)

print(type(enumerateGrocery))

# converting to list
print(list(enumerateGrocery))

# changing the default counter
enumerateGrocery = enumerate(grocery, 10)
print(list(enumerateGrocery))

<class 'enumerate'>
[(0, 'bread'), (1, 'milk'), (2, 'butter')]
[(10, 'bread'), (11, 'milk'), (12, 'butter')]


In [181]:
M = np.array([[1,2], [3,4]])
print(M)
print()


for row in M:
  print("row", row)
  for element in row:
    print(element)




[[1 2]
 [3 4]]

row [1 2]
1
2
row [3 4]
3
4


When we need to iterate over each element of an array and modify its elements, it is convenient to use
the enumerate function to obtain both the element and its index in the for loop

In [182]:
for row_idx, row in enumerate(M):
  print("row_idx", row_idx, "row", row)
  for col_idx, element in enumerate(row):
    print("col_idx", col_idx, "element", element)
      # update the matrix M: square each element
    M[row_idx, col_idx] = element ** 2

row_idx 0 row [1 2]
col_idx 0 element 1
col_idx 1 element 2
row_idx 1 row [3 4]
col_idx 0 element 3
col_idx 1 element 4


In [183]:
M

array([[ 1,  4],
       [ 9, 16]])

### 3.14 Using arrays in conditions

When using arrays in conditions,for example if statements and other boolean expressions, one needs to use
any or all, which requires that any or all elements in the array evalutes to True

In [190]:
M = np.array([[ 0, 4], [ 9, 16]])

In [187]:
if (M > 5).any():
  print("at least one element in M is larger than 5")
else:
  print("no element in M is larger than 5")

no element in M is larger than 5


In [191]:
if (M > 5).all():
  print("all elements in M are larger than 5")
else:
  print("all elements in M are not larger than 5")

all elements in M are larger than 5
