<a href="https://colab.research.google.com/github/sfragkoul/Intro/blob/main/4_Exercises_PUBLIC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Notebook by Stella Fragkouli based on exercises from [w3resource
](https://www.w3resource.com/python-exercises/). 


Aristotle University of Thessaloniki

v1.0 (March 2021)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


[numpy arrays depicted](https://www.w3resource.com/w3r_images/python-numpy-arrays-image.png)

### 1.
Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [ ]:
x = np.array([1, 0, 0, 0])
print(x)
print(np.any(x))

[1 0 0 0]
True


In [ ]:
x1=np.array([0, 0, 0, 0])
print(np.any(x1))

False


[Numpy any() ](https://drive.google.com/file/d/1adOAB3jlWdThioGdaTxp3JXUw0_tZius/view?usp=sharing)

### 2.

Create a list and fill it with odd numbers from 0 to 100


In [ ]:
M =[]

for i in range(0,100):
  if i%2!=0:
    M.append(i)
print(M)    

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [ ]:
N =[]

for i in range(0,50):
  n=2*i + 1
  N.append(n)
print(N)  

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


### 3.

Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a): #nditer is an efficient multi-dimensional iterator object to iterate over arrays. 
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

### 4.

Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [ ]:
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


### 5.

Write a NumPy program to create a vector with values ​​from 0 to 20 and change the sign of the numbers in the range from 9 to 15.

In [ ]:
x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) * (x <= 15)] *= -1
print(x)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


### 6.

Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


### 7. 

Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.


In [ ]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2)) #Return the unique, sorted array of values that are in either of the two input arrays

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


### 8. 

Write a NumPy program to calculate the absolute value element-wise.

In [ ]:
import math

x = np.array([math.cos(0), math.cos(math.pi)])
print("Original array:")
print(x)
print("Element-wise absolute value:")
print(np.absolute(x))

Original array:
[ 1. -1.]
Element-wise absolute value:
[1. 1.]


### 9.

Write a NumPy program to remove the negative values in a NumPy array with 0.

In [ ]:
x = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print("Original array:")
print(x)
print("Replace the negative values of the said array with 0:")
x[x<0] = 0
print(x)

Original array:
[-1 -4  0  2  3  4  5 -6]
Replace the negative values of the said array with 0:
[0 0 0 2 3 4 5 0]


### 10.

Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.  Select the elements from the second array corresponding to elements in the first array that are greater than 100 and less than 110

In [ ]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print("Original arrays")
print(a)
print(b)
print("Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:")
print(b[(100 < a) & (a < 110)])

Original arrays
[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
Elements from the second array  corresponding to elements in the first array  that are greater than 100 and less than 110:
['e' 'i']


### 11.

Write a NumPy program to count the frequency of unique values in NumPy array.

In [ ]:
a = np.array( [10,10,20,10,20,20,20,30, 30,50,40,40] )
print("Original array:")
print(a)
unique_elements, counts_elements = np.unique(a, return_counts=True)
print("Frequency of unique values of the said array:")
print(np.asarray((unique_elements, counts_elements))) #Convert the input to an array.
print((unique_elements, counts_elements))

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]
(array([10, 20, 30, 40, 50]), array([3, 4, 2, 2, 1]))


[counts](https://www.w3resource.com/w3r_images/python-numpy-image-exercise-94.png)